/// Flutter icons MachinesIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MachinesIcons
///      fonts:
///       - asset: fonts/MachinesIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MachinesIcons {
  MachinesIcons._();

  static const _kFontFam = 'MachinesIcons';
  static const String? _kFontPkg = null;

  static const IconData passadeira_down = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData passadeira_left = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData passadeira_right = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData produto_final = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotacao = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData separador_balistico = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData separador_focault = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData separador_otico_pe = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData separador_magnetico = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData separador_otico_pm = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triagem_manual_c = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triagem_manual_p = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triagem_manual_po = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triagem_manual_v1 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triagem_manual_v2 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData abre_sacos = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compactador = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crivo_de_discos = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entrada = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData juncao_caudais = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lixo = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
